# Generated by Django 6.0.5 on 2026-06-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
